# # Instruction
# - assign a new image name
# - make this file consistent with that in https://github.com/okatsn/MyTeXLife

services:
  # The service name should be consistent with that in devcontainer.json
  devqt:
    build:
      context: ..
      #     That is out of /.devcontainer
      # context: .
      #     That is /.devcontainer
      dockerfile: .devcontainer/Dockerfile

    # Better not to have duplicate image name
    image: jujuliaqt
    init: true
    # See https://docs.docker.com/compose/compose-file/compose-file-v3/#init

    # Better not to have duplicate container name. Error "Conflict will occur if another. The container name "/tex-with-julia" is already in use by container" might occur if there is another container of the same name is currently running.
    container_name: for-QuartoTemplates
    volumes:
      # # The home directory is called "workspace"; try `cd ..` and `ls` to figure it out.
      - ..:/home/jovyan/workspace
      # # WARNING: Docker socket to access Docker server
      # Docker command run inside the container actually communicates with the Docker engine on your host machine. This theoretically allows a malicious agent to grant root accessibility to your host machine by creating a new container and mounted it to the entire hard drive.
      # - /var/run/docker.sock:/var/run/docker.sock
      # # WARNING: Forwarding `.ssh`, `.gitconfig` and `pydrive2fs` (DVC token) allows agents in container to run `git push origin --delete` or `dvc gc -T`.
      # # WARNING: SSH directory
      # - ~/.ssh:/home/jovyan/.ssh
      # # For Windows without WSL, a copy will be made from /tmp/.ssh to ~/.ssh to fix permissions
      # - ~/.ssh:/tmp/.ssh:ro
      # # Copilot agents
      - ~/projects/my-agents:/home/jovyan/projects/my-agents:ro
      # Off-the-shelf skills
      - ~/ai-skills:/home/jovyan/ai-skills:ro
      # # WARNING: Git config
      # - ~/.gitconfig:/home/jovyan/.gitconfig
      # # Persistent volumes for this container; Avoid reinstall vscode extensions
      - julia-depot:/home/jovyan/.julia
      # # KEYNOTE:
      # # - Named volumes is chosen because VSCode extensions of this environment is not expected to be shared with those in WSL.
      # # - Please refer to okatsn/MyTeXLife for more explanation
      - vscode-server:/home/jovyan/.vscode-server
      # # WARNING: DVC credential cache directory (this makes DVC credential persistant)
      # - ~/.cache/pydrive2fs:/home/jovyan/.cache/pydrive2fs
    environment:
      # Set time zone (GMT-8 is UTC+8):
      # - To print available time-zone names: ls /usr/share/zoneinfo
      - TZ=Etc/GMT-8
    entrypoint: sh -c "sleep infinity"


# KEYNOTE: Those defined volumes in service should be declared in the root level
# Unbind vscode-server to volumes to ensure extensions in devcontainer.json to be installed on rebuild
volumes:
  julia-depot:
  vscode-server:
