project:
  type: website
  # render: 
  #   - index.qmd
  # # By default, it renders all qmd, md files.
  # See https://quarto.org/docs/websites/index.html#render-targets


website:
  title: "QuartoTemplates"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - others/about.qmd
      - others/website-how.md
  sidebar:
    style: "docked"
    # contents: auto
    # # All quarto markdown with "title" displayed on the side.
    # # use an explicit /* to indicate only the documents in the root directory: 
    contents: 
      - auto: /*


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



execute:
  freeze: auto
  # This make sure julia codes will be execute in local only. https://quarto.org/docs/publishing/github-pages.html#freezing-computations