name: Quarto Publish

on:
  workflow_dispatch:
  push:
    paths:
      - "*.qmd"
      - "*.md"
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Copy files before rendering
        run: . docs/cpfiles.sh

      # See https://github.com/quarto-dev/quarto-actions/blob/main/publish/action.yml
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
